# Generated by go2rpm

%bcond_without check



# https://github.com/10gen/escaper

%global goipath         github.com/10gen/escaper

Version:        0

%gometa


%global common_description %{expand:

Escaper lets you create your own formatting syntax. By design, expanding a

format string with this utility requires no additional arguments (unlike

fmt.Sprinf) by letting you easily register your own escape handlers. This makes

it ideal for configurability, where only a string is necessary to specify a

complex output format.}



%global golicenses      LICENSE

%global godocs          README.md



Name:           %{goname}


Release:        0.20220602082016103049.master%{?dist}

Summary:        Better abstraction for formatting output



License:        MIT

URL:            %{gourl}

Source0:        escaper-0.tar.gz



%description

%{common_description}



%gopkg


%prep

%goprep


%install

%gopkginstall


%if %{with check}

%check

%gocheck

%endif



%gopkgfiles


%changelog
* Thu Jun 02 2022 Laura Barcziova <lbarczio@redhat.com> - 0-0.20220602082016103049.master
- Development snapshot (5507cfd1)


* Thu Jan 20 2022 Fedora Release Engineering <releng@fedoraproject.org> - 0-0.11

- Rebuilt for https://fedoraproject.org/wiki/Fedora_36_Mass_Rebuild



* Thu Jul 22 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0-0.10

- Rebuilt for https://fedoraproject.org/wiki/Fedora_35_Mass_Rebuild



* Tue Jan 26 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0-0.9

- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild



* Mon Jul 27 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0-0.8

- Rebuilt for https://fedoraproject.org/wiki/Fedora_33_Mass_Rebuild



* Tue Jan 28 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0-0.7

- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild



* Thu Jul 25 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0-0.6

- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild



* Tue May 28 16:36:56 CEST 2019 Robert-André Mauchin <zebob.m@gmail.com> - 0-0.5.20180528git17fe61c

- Update to new macros



* Thu Jan 31 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0-0.4.git17fe61c

- Rebuilt for https://fedoraproject.org/wiki/Fedora_30_Mass_Rebuild



* Tue Oct 23 2018 Nicolas Mailhot <nim@fedoraproject.org> - 0-0.3.git17fe61c

- redhat-rpm-config-123 triggers bugs in gosetup, remove it from Go spec files as it’s just an alias

- https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/RWD5YATAYAFWKIDZBB7EB6N5DAO4ZKFM/



* Fri Jul 13 2018 Fedora Release Engineering <releng@fedoraproject.org> - 0-0.2.git17fe61c

- Rebuilt for https://fedoraproject.org/wiki/Fedora_29_Mass_Rebuild



* Thu May 31 2018 mskalick@redhat.com - 0-0.1.20180528git17fe61c

- Initial packaging for Fedora
